<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>toc</string>
	<key>fileTypes</key>
	<array>
		<string>toc</string>
	</array>

	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>^(##)\s*(Author|DefaultState|Dependencies|Interface|Load(?:OnDemand|With|Managers)|Notes(?:\-.{4})?|OptionalDeps|OptionalDependencies|RequiredDeps|RequiredDependencies|SavedVariables(?:PerCharacter)?|Secure|Title(?:\-.{4})?|Version)(\:)\s*(.*)$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.toc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.toc</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.toc</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.toc</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>^(##)\s*(X\-[^:\s]+)(\:)\s*(.*)$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.toc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.x.toc</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.toc</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.toc</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>(^#[^#]+)</string>
			<key>name</key>
			<string>comment.toc</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.toc</string>
	<key>uuid</key>
	<string>C22B105F-216F-4779-9E20-7C881A2B0C99</string>
</dict>
</plist>
